package oidc

const (
	COOKIE_STATE_NAME = "oidc_state"

	DEFAULT_RANDOM_STRING_LENGTH = 12

	ISSUER_ENV = "ISSUER_URL"

	NETLIFY_URL_ENV              = "URL"
	NETLIFY_DEPLOY_PRIME_URL_ENV = "DEPLOY_PRIME_URL"

	OIDC_CLIENT_ID_ENV     = "OIDC_CLIENT_ID"
	OIDC_CLIENT_SECRET_ENV = "OIDC_CLIENT_SECRET"

	RANDOM_ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

	URL_PATH_CALLBACK = "/callback"
)
